name: vscode
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: Code editing. Redefined.
description: |
  Visual Studio Code is a new choice of tool that combines the
  simplicity of a code editor with what developers need for the core
  edit-build-debug cycle.

grade: stable
confinement: classic

parts:
  vscode:
    plugin: dump
    source:
      - on amd64: https://go.microsoft.com/fwlink/?LinkID=760868
      - on i386: https://go.microsoft.com/fwlink/?LinkID=760680
      - on arm64: fail
      - on armhf: fail
    source-type: deb
    override-build: |
      ARCHITECTURE=$(dpkg --print-architecture)
      if [ "${ARCHITECTURE}" = "amd64" ]; then
        DEB_API="https://go.microsoft.com/fwlink/?LinkID=760868"
      elif [ "${ARCHITECTURE}" = "i386" ]; then
        DEB_API="https://go.microsoft.com/fwlink/?LinkID=760680"
      else
        echo "ERROR! Visual Studio Code only produces debs for amd64 and i386. Failing the build here."
        exit 1
      fi

      DEB_URL=$(curl -w "%{url_effective}\n" -I -L -s -S "${DEB_API}" -o /dev/null)
      VERSION=$(echo "${DEB_URL}" | cut -d'_' -f2)
      echo $VERSION > $SNAPCRAFT_STAGE/version

      # Correct path to icon.
      sed -i 's|Icon=code|Icon=/usr/share/pixmaps/code\.png|g' usr/share/applications/code.desktop
      snapcraftctl build
    build-packages:
      # Visual Studio Code is only publishes debs for amd64,
      # so fail the build on other architectures.
      - curl
      - dpkg
      - sed
    stage-packages:
      - libasound2
      - libgconf2-4
      - libgtk-3-0
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libsecret-1-0
      - libxss1
      - libxtst6
  electron-launch:
    plugin: dump
    source: files/

apps:
  vscode:
    command: bin/electron-launch ${SNAP}/usr/share/code/bin/code
    desktop: usr/share/applications/code.desktop
